// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportUp.DBContext;

namespace SportUp.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20190730101616_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportUp.Models.Player", b =>
                {
                    b.Property<int>("idPlayer")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cognome");

                    b.Property<int>("idTrainer");

                    b.Property<string>("nome");

                    b.HasKey("idPlayer");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SportUp.Models.Trainer", b =>
                {
                    b.Property<int>("idTrainer")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("password");

                    b.Property<string>("username");

                    b.HasKey("idTrainer");

                    b.ToTable("Trainers");
                });
#pragma warning restore 612, 618
        }
    }
}
