# Generated by Django 2.2.4 on 2019-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_prova'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allenamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lun', models.TextField()),
                ('mar', models.TextField()),
                ('mer', models.TextField()),
                ('gio', models.TextField()),
                ('ven', models.TextField()),
                ('sab', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lun', models.TextField()),
                ('mar', models.TextField()),
                ('mer', models.TextField()),
                ('gio', models.TextField()),
                ('ven', models.TextField()),
                ('sab', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Prova',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
