# Generated by Django 2.2.4 on 2019-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20190822_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cognome', models.TextField()),
                ('ruolo', models.TextField()),
            ],
        ),
    ]
